### ISSUE TITLE
Minor issue and many thanks 

### ISSUE THREAD

**Issue by Findus23** [scharissis/maze-solver-python#3]
Hi,

Thanks for the great maze solver. I had a ton of fun printing out a huge maze and seeing if scanning, postprocessing and solving is faster than manual solving (it is by far)

It works extremly well with scanned images: 
![maze2_final](https://user-images.githubusercontent.com/6266037/34444354-da65018e-eccd-11e7-86c2-f45b948c2fe3.png)

And while it's obviously not intended for high performance it's fun letting it run for 40 minutes for a huge 220x220 maze:
https://www.youtube.com/watch?v=ztIaL0cqmh4
![200_edited](https://user-images.githubusercontent.com/6266037/34444386-1eea8694-ecce-11e7-8273-10cfc97e01d5.png)

Tip: When writing shell-scripts use https://www.shellcheck.net/. It helps avoid common errors and fix issues like non working spaces (use `MAZE="$1"` and so on) and other odd issues (don't parse the output of `ls` and instead just use `for img in *.jpg`)

**Comment by scharissis** [comment]
I missed this, but saw it now and wanted to say that I'm glad you found it useful and I also appreciate the feedback.
I may take the time to update it and move to Python3 in the process.
Feel free to send me (or submit a PR) to include larger maze images to help benchmark.
