### ISSUE TITLE
Package gives error in example maze

### ISSUE THREAD

**Issue by JasperNaberman** [scharissis/maze-solver-python#7]
Maze image maze_801600.jpg is provided as an example but the package is not able to solve this maze. Instead it raises an error: No path found.

This also happens in user provided mazes.

**Comment by KajoKrummenacher** [comment]
Just checked and can confirm that the example works with fix #11.

**Comment by scharissis** [comment]
Thanks for reporting the issue @JasperNaberman .
Closing as it seems fixed.
